GET http://localhost:8000/api/products HTTP/1.1

###

POST http://localhost:8000/api/products HTTP/1.1
Content-Type: application/json

{
    "title": "Testing title",
    "price": 0.01,
    "description": "This is a test description"
}

###

DELETE http://localhost:8000/api/products/6062507074f6cd2a2c8e07da HTTP/1.1